# $FreeBSD: head/multimedia/gstreamer1-plugins-x265/Makefile 549657 2020-09-23 04:17:11Z mi $

PORTREVISION=	1
CATEGORIES=	multimedia

COMMENT=	GStreamer libx265 based H265 plugin

GST_PLUGIN=	x265
DIST=		bad

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer1-plugins

.include "${MASTERDIR}/Makefile"
