# $FreeBSD: head/multimedia/gstreamer1-plugins-x264/Makefile 554400 2020-11-07 15:49:38Z jbeich $

PORTREVISION=	2
CATEGORIES=	multimedia

COMMENT=	GStreamer libx264 based H264 plugin

GST_PLUGIN=	x264
DIST=		ugly

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer1-plugins

.include "${MASTERDIR}/Makefile"
