# $FreeBSD: head/devel/toml11/Makefile 569442 2021-03-29 08:53:27Z dch $

PORTNAME=		toml11
DISTVERSIONPREFIX=	v
DISTVERSION=		3.6.1
CATEGORIES=		devel

MAINTAINER=		dch@FreeBSD.org
COMMENT=		C++11 header-only toml parser & encoder

LICENSE=		MIT
LICENSE_FILE=		${WRKSRC}/LICENSE

USES=		compiler:c++17-lang cmake
USE_GITHUB=	yes
GH_ACCOUNT=	ToruNiina

.include <bsd.port.mk>
