# Created by: Piotr Florczyk <p.florczyk@adminworkshop.pl>
# $FreeBSD: head/devel/py-construct/Makefile 569405 2021-03-28 18:21:05Z ehaupt $

PORTNAME=	construct
PORTVERSION=	2.10.63
PORTEPOCH=	1
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	ehaupt@FreeBSD.org
COMMENT=	Python module for parsing and building of data structures

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE

USES=		python:3.6+
USE_PYTHON=	autoplist distutils
NO_ARCH=	yes

.include <bsd.port.mk>
