# $FreeBSD: head/multimedia/gstreamer1-plugins-resindvd/Makefile 529240 2020-03-27 11:23:42Z martymac $

PORTREVISION=	1
CATEGORIES=	multimedia

COMMENT=	GStreamer resindvd DVD playback plugin

GST_PLUGIN=	resindvd
DIST=		bad

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer1-plugins

.include "${MASTERDIR}/Makefile"
