# $FreeBSD: head/multimedia/gstreamer1-plugins-aom/Makefile 569067 2021-03-23 22:01:05Z jbeich $

PORTREVISION=	14
CATEGORIES=	multimedia

COMMENT=	GStreamer (libaom) plugin

GST_PLUGIN=	aom
DIST=		bad

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer1-plugins

.include "${MASTERDIR}/Makefile"
