# $FreeBSD: head/multimedia/gstreamer1-plugins-v4l2/Makefile 534176 2020-05-06 13:53:34Z cmt $

PORTREVISION=	1
CATEGORIES=	multimedia
PKGNAMESUFFIX=	1-plugins-v4l2

COMMENT=	GStreamer Video 4 Linux 2 source plugin

GST_PLUGIN=	gst_v4l2
DIST=		good

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer1-plugins

.include "${MASTERDIR}/Makefile"
