# $FreeBSD: head/multimedia/gstreamer1-plugins-vpx/Makefile 524224 2020-01-26 17:42:36Z kwm $

PORTREVISION=	0
CATEGORIES=	multimedia

COMMENT=	GStreamer vp8 codec plugin

GST_PLUGIN=	vpx
DIST=		good

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer1-plugins

.include "${MASTERDIR}/Makefile"
