# $FreeBSD: head/multimedia/gstreamer1-plugins-dvdread/Makefile 529240 2020-03-27 11:23:42Z martymac $

PORTREVISION=	1
CATEGORIES=	multimedia

COMMENT=	GStreamer DVD access plugin with libdvdread

GST_PLUGIN=	dvdread
DIST=		ugly

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer1-plugins

.include "${MASTERDIR}/Makefile"
