# $FreeBSD: head/devel/R-cran-cpp11/Makefile 569562 2021-03-30 15:54:29Z tota $

PORTNAME=	cpp11
PORTVERSION=	0.2.7
CATEGORIES=	devel
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	C++11 Interface for R's C Interface

LICENSE=	MIT

USES=		compiler:c++11-lang cran:auto-plist

.include <bsd.port.mk>
