# Created by: Bernhard Froehlich <decke@bluelife.at>
# $FreeBSD: head/multimedia/mythtv-frontend/Makefile 558199 2020-12-16 02:48:03Z kevans $

PKGNAMESUFFIX=	-${SLAVEPORT}

MAINTAINER=	ahicks@p-o.co.uk
COMMENT=	Homebrew PVR project (frontend only)

MASTERDIR=	${.CURDIR}/../../multimedia/mythtv
SLAVEPORT=	frontend
PLIST=		${.CURDIR}/pkg-plist

.include "${MASTERDIR}/Makefile"
