# $FreeBSD: head/multimedia/gstreamer1-plugins-hls/Makefile 535391 2020-05-16 10:51:32Z sunpoet $

PORTREVISION=	1
CATEGORIES=	multimedia

COMMENT=	GStreamer HTTP Live Streaming (HLS) plugin

GST_PLUGIN=	hls
DIST=		bad

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer1-plugins

.include "${MASTERDIR}/Makefile"
