# $FreeBSD: head/multimedia/mlt-qt5/Makefile 557839 2020-12-12 17:04:37Z thierry $

PORTREVISION=	1

USES=	qt:5 xorg
USE_CXXSTD=	c++11
USE_QT=		core gui svg widgets xml
USE_XORG=	x11
MASTERDIR=	${.CURDIR:H}/mlt
SLAVEPORT=	qt5

.include "${MASTERDIR}/Makefile"
