# $FreeBSD: head/multimedia/gstreamer1-plugins-msdk/Makefile 521038 2019-12-27 23:29:16Z jbeich $

PORTREVISION=	0
CATEGORIES=	multimedia

COMMENT=	GStreamer (Intel MediaSDK) plugin

GST_PLUGIN=	msdk
DIST=		bad

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer1-plugins

.include "${MASTERDIR}/Makefile"
