# $FreeBSD: head/multimedia/gstreamer1-plugins-openh264/Makefile 536180 2020-05-22 01:19:33Z jbeich $

PORTREVISION=	1
CATEGORIES=	multimedia

COMMENT=	GStreamer (openh264) plugin

GST_PLUGIN=	openh264
DIST=		bad

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer1-plugins

.include "${MASTERDIR}/Makefile"
